### ISSUE TITLE
How can i use this sample for my own created app

### ISSUE THREAD

**Issue by gvsharma** [msintuneappsdk/sample-intune-xamarin-ios#1]
Thanks fo this sample and i am using ADAL from my own azure login, i followed the process given in [here](https://docs.microsoft.com/en-us/intune/app-sdk-ios#configure-azure-active-directory-authentication-library-adal). I have enter my client id, redirecturi, authority.

But eventually I am getting the error as follows.

> Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration.

So i came to a conclusion that i still need some more guidance to finish it, can you please tell me that apart from this what else should i change to avoid the error?

**Comment by Kyle-Reis** [comment]
Hey @gvsharma, it sounds like you need to give your application access to the Intune MAM service in Azure Portal: 

1. Go to portal.azure.com and authenticate with an account that has appropriate permissions for your tenant.
2. Select the Azure Active Directory Service
3. Select "App Registrations"
4. Select your app.
5. Click "Settings"
6. Click "Required permissions"
7. Click the “Add” link
8. Click “Select an API”
9. In the search box enter “Microsoft Mobile Application Management”
10. Select “Microsoft Mobile Application Management” in the list of APIs and click "Select"
11.) Select “Read and Write the User’s App Management Data” and click "Select".
12. Click "Done", Click "Grant permissions", then click "Yes"

**Comment by gvsharma** [comment]
Hi @Kyle-Reis , I did what you have mentioned, now am getting another error: The error is as follows in iOS simulator in Alert.
"The Intune MAM sdk failed to connect to the location service to determine the users end point "

**Comment by Kyle-Reis** [comment]
Hey @gvsharma. Is the device enrolled with a different account from the one you were testing with?

**Comment by gvsharma** [comment]
I have created a fresh Microsoft ID and registered an app, created a user and followed the above steps and its working as expected.
Closing this
