### ISSUE TITLE
How to correct transfer file from outlook app to my app in intune MAM policy for iOS?

### ISSUE THREAD

**Issue by JamestsaiTW** [msintuneappsdk/sample-intune-xamarin-ios#3]
I had developed an app, **IntuneArchiver**, which is receiving file from outlook app in intune mam policy, but I got a problem.   

When I set intune App Protection for Data protection "Send org data to other apps" to "All apps" (like as below screenshot):
![image](https://user-images.githubusercontent.com/9651229/94541534-46155180-027a-11eb-8bc6-7e7bd5f96a7c.png)    

I try to use debugging in Visual Studio, I got the length of file is right:(like as below screenshot)  
![image](https://user-images.githubusercontent.com/9651229/94541487-3990f900-027a-11eb-8f9f-a55082acd36d.png)  

And this file in my App can work very well. 

When I set intune App Protection for Data protection "Send org data to other apps" to "Policy managed apps" (like as below screenshot):  
![image](https://user-images.githubusercontent.com/9651229/94541663-6b09c480-027a-11eb-8bf4-b42a39661270.png)  
I try to use debugging in Visual Studio, I got the length of file is wrong:(like as below screenshot)   
![image](https://user-images.githubusercontent.com/9651229/94541780-912f6480-027a-11eb-899b-69921adfafff.png)  

Then this file can't work right in my app.   

How to correct it for _Intune App Protection for Data protection "Send org data to other apps" is "Policy managed apps"_?

**Comment by Kyle-Reis** [comment]
Hi @JamestsaiTW, is this issue occurring in the extension for your app?

**Comment by JamestsaiTW** [comment]
Hi @Kyle-Reis, it really can't work right in the extension for my app.   

But I want to know how to get right file size, when "Send org data to other apps" is "Policy managed apps". It seems adding _something_ for the file when transfer file from outlook app to my app. This _something_ causes work right in the extension for my app.

**Comment by JamestsaiTW** [comment]
Is there any workaround?

**Comment by Kyle-Reis** [comment]
Hi @JamestsaiTW, does your app extension link to the Intune SDK? When this policy is configured, Intune will encrypt all data that is shared out of the application, so that only applications/extensions which link to the Intune SDK can decrypt the data. It sounds like the file is not being decrypted in your extension, possibly because it does not link to the Intune SDK. You'll need to be sure to link both the app and the extension to Intune.

**Comment by JamestsaiTW** [comment]
Hi @Kyle-Reis , I use [sharpcompress](https://github.com/adamhathcock/sharpcompress) in my App. As your reply, It means I need to link [sharpcompress](https://github.com/adamhathcock/sharpcompress) to the Intune SDK? 

BTW, My app works well in the same feature on Android.

Thanks for your reply.

**Comment by Kyle-Reis** [comment]
Hey @JamestsaiTW, could you describe the exact scenario a bit more and explain exactly where/how things are broken? When does this issue occur? Is it when some file is being shared from another application into your application? Or is this a file that your application creates directly and attempts to display?

**Comment by Kyle-Reis** [comment]
From the original description, it sounds like the file is being shared from Outlook. Is that sharing happening via some extension that you have implemented for your application?

**Comment by JamestsaiTW** [comment]
Hi @Kyle-Reis, thanks for your relpy.

The following steps and screenshots are my exact scenario:  
**First**, I open Outlook App (MAM by Intune policy).  

**Second**, I got an email (maybe attached a normal zip file) in Outlook App and I try to open it by my app (MAM by Intune policy):
![Second Step](https://user-images.githubusercontent.com/9651229/102534698-273c9380-40e2-11eb-9b36-2a3a277b58fd.png)

**Third**, I transfer it (zip file) to my app and unarchive it:
![Third Step](https://user-images.githubusercontent.com/9651229/102535993-f3626d80-40e3-11eb-9994-028e75449f37.png)

When I got this error(or exception), I try to look it in Visual Studio by Debug Mode.
Now, I understand I got a different file (it's an encrypt file) in my app, so I can't unarchive it well done.

How do I solve it?

**Comment by Kyle-Reis** [comment]
Hi @JamestsaiTW,  has the IntuneArchiver app successfully been enrolled in Intune MAM with the same account as Outlook?

**Comment by JamestsaiTW** [comment]
I think "YES".

Or how to check it in my Intune environment settings?

**Comment by Kyle-Reis** [comment]
@JamestsaiTW, is the app calling either of the [Intune enrollment methods](https://docs.microsoft.com/mem/intune/developer/app-sdk-xamarin#enabling-intune-app-protection-polices-in-your-ios-mobile-app)?

**Comment by JamestsaiTW** [comment]
@Kyle-Reis My app didn't call it. I will try it in next week. Thanks!

**Comment by JamestsaiTW** [comment]
@Kyle-Reis Thanks for your reply. Because my app is implemented by Xamarin.Forms, I miss calling either of the [Intune enrollment methods](https://docs.microsoft.com/mem/intune/developer/app-sdk-xamarin#enabling-intune-app-protection-polices-in-your-ios-mobile-app) for iOS (project/App). It's work well down now, thanks!
