### ISSUE TITLE
This sample code fails when the Intune SDK is updated to latest

### ISSUE THREAD

**Issue by MikeP0911** [msintuneappsdk/sample-intune-xamarin-ios#4]
Will this sample code run till Intune SDK version 14.3.5 only?
It fails for the latest Intune SDK version

**Comment by Kyle-Reis** [comment]
Hi @MikeP0911 - I am able to build and run the application after upgrading to the current Intune Xamarin.iOS bindings (17.1.1). I've pushed those changes out to the remote. Could you let me know if you're still having trouble building the sample app? If so, could you provide error details? Thanks!

**Comment by MikeP0911** [comment]
@Kyle-Reis Below are the warnings

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NETSDK1138	The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.	SharpCompress	C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets	28	

Warning		Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.
There was a conflict between "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Microsoft.CSharp.dll].
        C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Microsoft.CSharp.dll
          Project file item includes which caused reference "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Microsoft.CSharp.dll".
            Microsoft.CSharp
    References which depend on "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
        C:\Users\veluchamy.rathika\.nuget\packages\csvhelper\27.2.1\lib\netstandard2.1\CsvHelper.dll
          Project file item includes which caused reference "C:\Users\veluchamy.rathika\.nuget\packages\csvhelper\27.2.1\lib\netstandard2.1\CsvHelper.dll".
            C:\Users\veluchamy.rathika\.nuget\packages\csvhelper\27.2.1\lib\netstandard2.1\CsvHelper.dll
            C:\TFS Source\LicenseKanri\ZipExtractor\ZipExtractor\ZipExtractor\bin\A1_0_LicenseDebug\netstandard2.0\ZipExtractor.dll
        C:\Users\veluchamy.rathika\.nuget\packages\microsoft.identitymodel.clients.activedirectory\5.2.9\lib\xamarinios10\Microsoft.IdentityModel.Clients.ActiveDirectory.dll
          Project file item includes which caused reference "C:\Users\veluchamy.rathika\.nuget\packages\microsoft.identitymodel.clients.activedirectory\5.2.9\lib\xamarinios10\Microsoft.IdentityModel.Clients.ActiveDirectory.dll".
            C:\Users\veluchamy.rathika\.nuget\packages\microsoft.identitymodel.clients.activedirectory\5.2.9\lib\xamarinios10\Microsoft.IdentityModel.Clients.ActiveDirectory.dll	ZipExtractor.iOS			

Warning		The app icon set "AppIcons_ZipExtractor" has 9 unassigned children.	ZipExtractor.iOS			

Warning		warning: dylib (/Users/user1/Library/Caches/Xamarin/mtbs/builds/ZipExtractor.iOS/abaa0656008ad72677ac56a932594932cb43a636387f36971cf878185b335679/obj/iPhone/A1_0_LicenseDebug/device-builds/ipad6.11-16.2/mtouch-cache/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub) was built for newer iOS version (13.0) than being linked (12.0)	ZipExtractor.iOS			

Warning		Debugging symbol file for '/Users/user1/Library/Caches/Xamarin/mtbs/builds/ZipExtractor.iOS/abaa0656008ad72677ac56a932594932cb43a636387f36971cf878185b335679/bin/iPhone/A1_0_LicenseDebug/device-builds/ipad6.11-16.2/ZipExtractor.dll' is not valid and was ignored.	ZipExtractor.iOS			

Warning		Debugging symbol file for '/Users/user1/Library/Caches/Xamarin/mtbs/builds/ZipExtractor.iOS/abaa0656008ad72677ac56a932594932cb43a636387f36971cf878185b335679/bin/iPhone/A1_0_LicenseDebug/device-builds/ipad6.11-16.2/ZipExtractor.dll' is not valid and was ignored.	ZipExtractor.iOS			

Warning		warning: dylib (/Users/user1/Library/Caches/Xamarin/mtbs/builds/ZipExtractor.iOS/abaa0656008ad72677ac56a932594932cb43a636387f36971cf878185b335679/obj/iPhone/A1_0_LicenseDebug/device-builds/ipad6.11-16.2/mtouch-cache/IntuneMAMSwift.framework/IntuneMAMSwift) was built for newer iOS version (13.0) than being linked (12.0)	ZipExtractor.iOS			

Warning		The project 'SharpCompress' cannot be referenced. The referenced project is targeted to a different framework family (.NETFramework)	ZipExtractor.iOS			

Warning	NU1605	Detected package downgrade: Xamarin.Forms from 5.0.0.2545 to 5.0.0.2401. Reference the package directly from the project to select a different version. 
 ZipExtractoriOS -> ZipExtractor -> Xamarin.Forms (>= 5.0.0.2545) 
 ZipExtractoriOS -> Xamarin.Forms (>= 5.0.0.2401)			1	

Warning	NU1605	Detected package downgrade: CsvHelper from 27.2.1 to 21.2.0. Reference the package directly from the project to select a different version. 
 ZipExtractor.AndroidTest -> ZipExtractor -> CsvHelper (>= 27.2.1) 
 ZipExtractor.AndroidTest -> CsvHelper (>= 21.2.0)			1	

Warning	NU1605	Detected package downgrade: Newtonsoft.Json from 13.0.1 to 12.0.3. Reference the package directly from the project to select a different version. 
 ZipExtractor.Android -> ZipExtractor -> Newtonsoft.Json (>= 13.0.1) 
 ZipExtractor.Android -> Newtonsoft.Json (>= 12.0.3)			1	

Warning	NU1605	Detected package downgrade: Xamarin.Forms from 5.0.0.2545 to 4.4.0.991757. Reference the package directly from the project to select a different version. 
 ZipExtractor.Android -> ZipExtractor -> Xamarin.Forms (>= 5.0.0.2545) 
 ZipExtractor.Android -> Xamarin.Forms (>= 4.4.0.991757)			1	

Warning	NU1605	Detected package downgrade: Xamarin.Essentials from 1.7.4 to 1.6.1. Reference the package directly from the project to select a different version. 
 ZipExtractor.UWP -> ZipExtractor -> Xamarin.Essentials (>= 1.7.4) 
 ZipExtractor.UWP -> Xamarin.Essentials (>= 1.6.1)			1	

Warning	NU1605	Detected package downgrade: NLog.Config from 4.7.15 to 4.7.7. Reference the package directly from the project to select a different version. 
 ZipExtractor.Android -> ZipExtractor -> NLog.Config (>= 4.7.15) 
 ZipExtractor.Android -> NLog.Config (>= 4.7.7)			1	

Warning	NU1605	Detected package downgrade: Newtonsoft.Json from 13.0.1 to 12.0.3. Reference the package directly from the project to select a different version. 
 ZipExtractor.AndroidTest -> ZipExtractor -> Newtonsoft.Json (>= 13.0.1) 
 ZipExtractor.AndroidTest -> Newtonsoft.Json (>= 12.0.3)			1	

Warning	NU1605	Detected package downgrade: Xamarin.Essentials from 1.7.4 to 1.7.3. Reference the package directly from the project to select a different version. 
 ZipExtractoriOS -> ZipExtractor -> Xamarin.Essentials (>= 1.7.4) 
 ZipExtractoriOS -> Xamarin.Essentials (>= 1.7.3)			1

**Comment by MikeP0911** [comment]
Hi @Kyle-Reis thank you for the reply. When i deploy i get an Error message - Unexpected failure.

**Comment by MikeP0911** [comment]
Hi @Kyle-Reis with 17.1.1 Intune SDK version, I get Error. Unexpected failure. Contact your IT administrator for help.
message box when login with username and password.

But with 14.3.5 No Error. Login successful.

**Comment by MikeP0911** [comment]
I tried running this sample code. When I click the login button, I could not get the next page.
There is an error.
Could you please guide me.

**Comment by MikeP0911** [comment]
![803E4BD4-E669-44A6-BB4C-D6F4370AA293](https://github.com/msintuneappsdk/sample-intune-xamarin-ios/assets/117801555/1ba30f88-b3c9-445d-abdd-c478b31a85d0)

**Comment by gastaffo** [comment]
Sorry for the long delay. Is this issue still occuring?

**Comment by MikeP0911** [comment]
@gastaffo 
Thank you. This is resolved now.
